name: Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Brent-Tunnicliff/action-setup-android@v1
      - uses: Brent-Tunnicliff/action-build-and-test-android@v1
      - uses: Brent-Tunnicliff/action-publish-lib-android@v1